### ISSUE TITLE
THIS ERROR IS COMMING IN CERTIFICATION

### ISSUE THREAD

**Issue by cptn11** [vcodes-xyz/bot-list#10]
TypeError: /home/runner/benedict/src/views/botlist/apps/certification.ejs:21
    19|                 <br>&raquo&raquo For bots

    20|                 <br>&raquo A special role on our Discord server to let people know that it's certified.

 >> 21|                 <br>&raquoA special badge(                <span data-tooltip="<%=bot.guilds.cache.get(config.serverID).roles.cache.get(roles.certified_bot).name%>" data-tooltip-location="top"> 

    22|                     <i class="fad fa-badge-check has-text-primary" style="font-size: 20px;"></i>

    23|                     </span>) on your bot card to let people know that it's certified.

    24|                 

Cannot read property 'roles' of undefined
    at eval (eval at compile (/home/runner/benedict/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:11:62)
    at certification (/home/runner/benedict/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/home/runner/benedict/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/home/runner/benedict/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/home/runner/benedict/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/runner/benedict/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/runner/benedict/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/runner/benedict/node_modules/express/lib/response.js:1012:7)
    at renderTemplate (/home/runner/benedict/src/server.js:73:9)
    at /home/runner/benedict/src/server.js:566:11
    at Layer.handle [as handle_request] (/home/runner/benedict/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/benedict/node_modules/express/lib/router/route.js:137:13)
    at checkAuth (/home/runner/benedict/src/server.js:77:41)
    at Layer.handle [as handle_request] (/home/runner/benedict/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/benedict/node_modules/express/lib/router/route.js:137:13)
    at checkMaintence (/home/runner/benedict/src/server.js:100:11)

**Comment by clqu** [comment]
Update your site and fill the roles
