### ISSUE TITLE
Getting `a.edit` error

### ISSUE THREAD

**Issue by Kyro3400** [vcodes-xyz/bot-list#11]
SO i have looked up on google on how to fix this error, but nothing works please someone help! Here is the error:
```
(node:364) UnhandledPromiseRejectionWarning: TypeError: a.edit is not a function
    at /home/runner/bot-list/src/server.js:1155:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /home/runner/bot-list/src/server.js:1154:9
```
(also i am using https://replit.com to host)

**Comment by dhvitish** [comment]
Give the 1155th line of server.js

**Comment by Kyro3400** [comment]
> Give the 1155th line of server.js

```
app.post("/admin/unmaintence", checkMaintence, checkAdmin, checkAuth, async (req, res) => {
    const dc = require("discord.js");
    if (!config.bot.owners.includes(req.user.id)) return res.redirect('../admin');
    let bakimdata = await maintenceSchema.findOne({
      server: config.server.id
    }); <- 1155th line
```

**Comment by clqu** [comment]
You get an error because the message is invalid, make sure you have filled the config correctly and has maintenance data.
