### ISSUE TITLE
Add server does not work and random errors

### ISSUE THREAD

**Issue by RachaelSmith2** [vcodes-xyz/bot-list#20]
TokenError: Invalid "code" in request.
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/runner/bot-list-5/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/runner/bot-list-5/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /home/runner/bot-list-5/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /home/runner/bot-list-5/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/runner/bot-list-5/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/runner/bot-list-5/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

----
Add server error;

403
To do this, you have to join our discord server.
And I am already in my discord server....

**Comment by clqu** [comment]
Open your bot intents or check your server id.
