### ISSUE TITLE
cant seem to load wenbsite css or pass a login

### ISSUE THREAD

**Issue by kkakealess** [vcodes-xyz/bot-list#54]
this is the error i get on the page after trying to login 

```
node v12.16.1
TypeError: /home/runner/uplist/src/views/index.ejs:1
 >> 1| <%- include('parts/head.ejs', {bot, user, path}) %>
    2| <%- include('parts/section') %>
    3| 
    4| 

/home/runner/uplist/src/views/parts/head.ejs:96
    94|             <a class="dropdown-item" href="/uptime/links"><i class="fal fa-sync-alt"></i>&nbsp;Uptime</a>
    95|             <% if(user) { %>
 >> 96|                 <% 
    97|                 let guild = bot.guilds.cache.get(config.server.id).members.cache.get(user.id);
    98|                 if(guild) {
    99|                 if(guild.roles.cache.get(roles.administrator) || guild.roles.cache.get(roles.moderator)) {

Cannot read property 'members' of undefined
    at eval (eval at compile (/home/runner/uplist/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:36:67)
    at head (/home/runner/uplist/node_modules/ejs/lib/ejs.js:692:17)
    at include (/home/runner/uplist/node_modules/ejs/lib/ejs.js:690:39)
    at eval (eval at compile (/home/runner/uplist/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:8:17)
    at index (/home/runner/uplist/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/home/runner/uplist/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/home/runner/uplist/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/home/runner/uplist/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/runner/uplist/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/runner/uplist/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/runner/uplist/node_modules/express/lib/response.js:1012:7)
    at ServerResponse.res.render (/home/runner/uplist/node_modules/express-minify-html-terser/minifier.js:82:16)
    at /home/runner/uplist/src/routers/index.js:7:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by kkakealess** [comment]
fixed i had to enable intents
