### ISSUE TITLE
Discord Buttons Error

### ISSUE THREAD

**Issue by builtbyjonas** [vcodes-xyz/bot-list#86]
can someone help me to fix this?

/home/runner/stoneclane/node_modules/discord-buttons/src/v12/Classes/interfaces/BaseMessageComponent.js:28
                throw new SyntaxError('INVALID_TYPE: Invalid MessageComponentType');
                ^

SyntaxError: INVALID_TYPE: Invalid MessageComponentType
    at Function.create (/home/runner/stoneclane/node_modules/discord-buttons/src/v12/Classes/interfaces/BaseMessageComponent.js:28:23)
    at /home/runner/stoneclane/node_modules/discord-buttons/src/v12/Classes/MessageActionRow.js:18:77
    at Array.map (<anonymous>)
    at MessageActionRow.setup (/home/runner/stoneclane/node_modules/discord-buttons/src/v12/Classes/MessageActionRow.js:18:47)
    at new MessageActionRow (/home/runner/stoneclane/node_modules/discord-buttons/src/v12/Classes/MessageActionRow.js:8:14)
    at Function.create (/home/runner/stoneclane/node_modules/discord-buttons/src/v12/Classes/interfaces/BaseMessageComponent.js:19:29)
    at /home/runner/stoneclane/node_modules/discord-buttons/src/v12/Classes/Message.js:10:81
    at Array.map (<anonymous>)
    at ExtendedMessage._patch (/home/runner/stoneclane/node_modules/discord-buttons/src/v12/Classes/Message.js:10:51)
    at new Message (/home/runner/stoneclane/node_modules/discord.js/src/structures/Message.js:44:20)
    at new ExtendedMessage (/home/runner/stoneclane/node_modules/discord-buttons/src/v12/Classes/Message.js:6:1)
    at MessageManager.add (/home/runner/stoneclane/node_modules/discord.js/src/managers/BaseManager.js:49:32)
    at MessageManager.add (/home/runner/stoneclane/node_modules/discord.js/src/managers/MessageManager.js:30:18)
    at MessageCreateAction.handle (/home/runner/stoneclane/node_modules/discord.js/src/client/actions/MessageCreate.js:13:40)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/stoneclane/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/stoneclane/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)

**Comment by AstroApex22** [comment]
I will have a look into this and try and resolve this for you.
