### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by builtbyjonas** [vcodes-xyz/bot-list#88]
/home/runner/stoneclane/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/home/runner/stoneclane/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/home/runner/stoneclane/node_modules/bindings/bindings.js:112:48)
    at new Database (/home/runner/stoneclane/node_modules/better-sqlite3/lib/database.js:48:64)
    at Object.<anonymous> (/home/runner/stoneclane/node_modules/quick.db/src/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/stoneclane/node_modules/quick.db/index.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
exit status 1
 

Does anybody know how to fix? Pls help @clqu

**Comment by AstroApex22** [comment]
Ensure you are using Node 12.
