### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by BallisticOK** [vcodes-xyz/bot-list#90]

**Comment by BallisticOK** [comment]
oops sorry forgot to add a description
but

i got 




npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/void.db/-/void.db-2.0.4.tgz
npm ERR! 404
npm ERR! 404  'void.db@2.0.4' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'vcodes-4'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ashfl\AppData\Roaming\npm-cache\_logs\2022-03-26T09_46_08_920Z-debug.log



then i try to install discord.js

**Comment by builtbyjonas** [comment]
simply go to package.json and remove the void.db package and install again with the ```npm install``` command

**Comment by BallisticOK** [comment]
thx
i do have some other problems

**Comment by BallisticOK** [comment]
the admin/maintence and admin/partner cind work
both give me
![image](https://user-images.githubusercontent.com/39306849/160395518-4ff1818d-2b76-42d8-be56-c598d6966ad1.png)

**Comment by anshtyagi0** [comment]
check console that have you got any error.

> the admin/maintence and admin/partner cind work
> both give me
> ![image](https://user-images.githubusercontent.com/39306849/160395518-4ff1818d-2b76-42d8-be56-c598d6966ad1.png)

**Comment by BallisticOK** [comment]
the maintence one dont give any errors at all


BUT

the patner one gives


(node:37) UnhandledPromiseRejectionWarning: ReferenceError: path is not defined
    at /home/container/src/routers/admin/partner.js:10:29
    at Layer.handle [as handle_request] (/home/container/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/container/node_modules/express/lib/router/route.js:137:13)
    at global.checkAuth (/home/container/src/server.js:93:41)
    at Layer.handle [as handle_request] (/home/container/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/container/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/container/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/container/node_modules/express/lib/router/layer.js:95:5)
    at /home/container/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/container/node_modules/express/lib/router/index.js:341:12)
    at next (/home/container/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/container/node_modules/express/lib/router/index.js:174:3)
    at router (/home/container/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/container/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/container/node_modules/express/lib/router/index.js:323:13)
    at /home/container/node_modules/express/lib/router/index.js:284:7
(node:37) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by anshtyagi0** [comment]
Send the codes of your /home/container/src/routers/admin/partner.js

> the maintence one dont give any errors at all
> 
> BUT
> 
> the patner one gives
> 
> (node:37) UnhandledPromiseRejectionWarning: ReferenceError: path is not defined at /home/container/src/routers/admin/partner.js:10:29 at Layer.handle [as handle_request] (/home/container/node_modules/express/lib/router/layer.js:95:5) at next (/home/container/node_modules/express/lib/router/route.js:137:13) at global.checkAuth (/home/container/src/server.js:93:41) at Layer.handle [as handle_request] (/home/container/node_modules/express/lib/router/layer.js:95:5) at next (/home/container/node_modules/express/lib/router/route.js:137:13) at Route.dispatch (/home/container/node_modules/express/lib/router/route.js:112:3) at Layer.handle [as handle_request] (/home/container/node_modules/express/lib/router/layer.js:95:5) at /home/container/node_modules/express/lib/router/index.js:281:22 at Function.process_params (/home/container/node_modules/express/lib/router/index.js:341:12) at next (/home/container/node_modules/express/lib/router/index.js:275:10) at Function.handle (/home/container/node_modules/express/lib/router/index.js:174:3) at router (/home/container/node_modules/express/lib/router/index.js:47:12) at Layer.handle [as handle_request] (/home/container/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/home/container/node_modules/express/lib/router/index.js:323:13) at /home/container/node_modules/express/lib/router/index.js:284:7 (node:37) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:37) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by builtbyjonas** [comment]
> 

make sure you have added the partner role id. so it will work to 100% when you added every role id
