### ISSUE TITLE
InternalOAuthError: Failed to fetch user's guilds

### ISSUE THREAD

**Issue by dobrejpokus** [vcodes-xyz/bot-list#95]
Every time when I try to log in, this happends:
```
InternalOAuthError: Failed to fetch user's guilds
    at C:\Users\pedre\Desktop\benedict-4\node_modules\passport-discord\lib\strategy.js:108:32
    at passBackControl (C:\Users\pedre\Desktop\benedict-4\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\pedre\Desktop\benedict-4\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by builtbyjonas** [comment]
the reason for this issue can be that the discord.js package stopped working (v11 & v12). You can upgrade the code to v13 but then you have a bit work with recoding a few things. Or you simply wait until vcodes v5 gets released, because then it will be discord.js v13 i think

**Comment by builtbyjonas** [comment]
i have the problem too. But it logs you in otherwise. You only have to open your website again
